use_frameworks!

target 'RedOctober_Example' do
  pod 'RedOctober', :path => '../'

  target 'RedOctober_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  end
end
